spring:
  thymeleaf:
    prefix: classpath:/statics/
  redis:
    host: 127.0.0.1
    port: 6379
    password: linktrace
#    password: gdrcugmf
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/operation?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
#    url: jdbc:mysql://47.106.68.205:3306/operation?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
#    password: root
  jpa: 
    hibernate: 
      #更新或者创建数据表结构
      ddl-auto: update
      #控制台显示SQL
      show-sql: true
#server配置    
server:
#  port: 8080
  port: 80
operation:
  domain-url: http://trace.hk-fruitful.com